Set useless (but mandatory) parameters as so for gcc with the __attribute__((unused)).
This fix:
lib/tools/getBID.c: In function ‘py_getBID’:
lib/tools/getBID.c:32:32: error: unused parameter ‘self’ [-Werror=unused-parameter]
lib/tools/getBID.c:32:48: error: unused parameter ‘noarg’ [-Werror=unused-parameter]

Change-Id: I213ccecc6da062d8e7bcf50bef0790bdb30b6928