Explicitly declare 'self' parameters as unused to prevent GCC to through an error for no reason.
This prevent GCC from throwing:
lib/libNeedleman/Py_lib/libNeedleman.c: In function ‘py_alignMessages’:
lib/libNeedleman/Py_lib/libNeedleman.c:61:38: error: unused parameter ‘self’ [-Werror=unused-parameter]
lib/libNeedleman/Py_lib/libNeedleman.c: In function ‘py_alignTwoMessages’:
lib/libNeedleman/Py_lib/libNeedleman.c:157:41: error: unused parameter ‘self’ [-Werror=unused-parameter]